In [2]:
pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip3 install --upgrade pip

In [3]:
import numpy as np

In [4]:
a = np.array([0, 1, 2, 3])

In [5]:
print(a)

[0 1 2 3]


In [6]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


Memory-efficient and provides fast numerical operations

In [7]:
# Python List
L = range(1000)
%timeit [i**2 for i in L]

30.2 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
a = np.arange(1000)
%timeit a**2

528 ns ± 8.15 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
# 1-D 
a = np.array([0, 1, 2, 3])
a 

array([0, 1, 2, 3])

In [10]:
# print dimensions

a.ndim

1

In [11]:
a.shape

(4,)

In [12]:
len(a)

4

In [13]:
# 2-D, 3-D 

b = np.array([[0, 1, 2], [3, 4, 5]])
b 

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b) # returns the size of the first dimension 

2

In [17]:
c = np.array([[[0,1], [2,3], [4,5], [6,7]]])

c

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [18]:
c.ndim

3

In [19]:
c.shape

(1, 4, 2)

In [20]:
len(c)

1

In [21]:
# using arange function

a = np.arange(10) # 0....n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.arange(1, 10, 2) 
b

array([1, 3, 5, 7, 9])

In [23]:
# using linspace

a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
# common arrays

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
c = np.eye(3) # returns a 2-D array with ones on the diagonal and zeros elsewhere.
c 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
d = np.eye(3, 2) # 3 is number of rows, 2 is number of columns, index of diagonal starts with 0
d 

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [28]:
# create an array using diag function

a = np.diag([1, 2, 3, 4]) # construct a diagonal array

a 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
np.diag(a)

array([1, 2, 3, 4])

In [30]:
# create array using random
# create an array of the given shape and populate it with random samples from a uniform distribution over
# [0, 1)
a = np.random.rand(4) 
a 

array([0.76178513, 0.50561659, 0.91669443, 0.12017943])

In [31]:
a = np.random.randn(4) #breturn a sample from "Standard Normal distribution" or Gaussian distribution
a 

array([ 1.06903116,  1.03830443, -0.93941042, -0.77160401])